version: '3'

services:
  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./web:/web
      - static_volume:/web/static
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      POSTGRES_USER: lifesabeach
      POSTGRES_PASSWORD: lifesabeach
      POSTGRES_DB: lifesabeach
      DATABASE_URL: postgresql://lifesabeach:lifesabeach@db/lifesabeach
    depends_on:
      - db
    networks:
      - postgres

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: lifesabeach
      POSTGRES_PASSWORD: lifesabeach
      POSTGRES_DB: lifesabeach
    volumes:
      - db_volume:/var/lib/postgresql/data
    networks:
      - postgres

volumes:
  db_volume:
  static_volume:

networks:
  postgres:
    driver: bridge
